# TODO 将友情站点做成list， 而不是只有一个 @gaohui 2014-03-21
#站点地图友情链接
#第一个配置项:站点ID;
#第二个配置项:站点名称:链接URL;
#第三，四个配置项分别为经纬度;
#秦始皇帝陵博物院


#qinshihuang:
#  - "61011501"
#  - 秦始皇帝陵博物院:http://124.115.173.6/galaxy
#  - "109.289895"
#  - "34.389353"