
package com.microwise.saturn.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IRpService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IRpService {


    /**
     * 
     * @param startDate
     * @param endDate
     * @return
     *     returns com.microwise.saturn.webservice.ArrayOfMaterialSummary
     */
    @WebMethod(operationName = "GetSummaryWithRelicMaterial", action = "http://tempuri.org/IRpService/GetSummaryWithRelicMaterial")
    @WebResult(name = "GetSummaryWithRelicMaterialResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSummaryWithRelicMaterial", targetNamespace = "http://tempuri.org/", className = "com.microwise.saturn.webservice.GetSummaryWithRelicMaterial")
    @ResponseWrapper(localName = "GetSummaryWithRelicMaterialResponse", targetNamespace = "http://tempuri.org/", className = "com.microwise.saturn.webservice.GetSummaryWithRelicMaterialResponse")
    public ArrayOfMaterialSummary getSummaryWithRelicMaterial(
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
            XMLGregorianCalendar startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
            XMLGregorianCalendar endDate);

    /**
     * 
     * @param startDate
     * @param relicMaterial
     * @param endDate
     * @return
     *     returns com.microwise.saturn.webservice.ArrayOfRelicData
     */
    @WebMethod(operationName = "GetListByRelicMaterial", action = "http://tempuri.org/IRpService/GetListByRelicMaterial")
    @WebResult(name = "GetListByRelicMaterialResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetListByRelicMaterial", targetNamespace = "http://tempuri.org/", className = "com.microwise.saturn.webservice.GetListByRelicMaterial")
    @ResponseWrapper(localName = "GetListByRelicMaterialResponse", targetNamespace = "http://tempuri.org/", className = "com.microwise.saturn.webservice.GetListByRelicMaterialResponse")
    public ArrayOfRelicData getListByRelicMaterial(
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
            XMLGregorianCalendar startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
            XMLGregorianCalendar endDate,
            @WebParam(name = "relicMaterial", targetNamespace = "http://tempuri.org/")
            String relicMaterial);

    /**
     * 
     * @param startDate
     * @param endDate
     * @return
     *     returns com.microwise.saturn.webservice.ArrayOfOwnerSummary
     */
    @WebMethod(operationName = "GetSummaryWithOwner", action = "http://tempuri.org/IRpService/GetSummaryWithOwner")
    @WebResult(name = "GetSummaryWithOwnerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetSummaryWithOwner", targetNamespace = "http://tempuri.org/", className = "com.microwise.saturn.webservice.GetSummaryWithOwner")
    @ResponseWrapper(localName = "GetSummaryWithOwnerResponse", targetNamespace = "http://tempuri.org/", className = "com.microwise.saturn.webservice.GetSummaryWithOwnerResponse")
    public ArrayOfOwnerSummary getSummaryWithOwner(
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
            XMLGregorianCalendar startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
            XMLGregorianCalendar endDate);

    /**
     * 
     * @param startDate
     * @param ownerId
     * @param endDate
     * @return
     *     returns com.microwise.saturn.webservice.ArrayOfRelicData
     */
    @WebMethod(operationName = "GetListByOwner", action = "http://tempuri.org/IRpService/GetListByOwner")
    @WebResult(name = "GetListByOwnerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetListByOwner", targetNamespace = "http://tempuri.org/", className = "com.microwise.saturn.webservice.GetListByOwner")
    @ResponseWrapper(localName = "GetListByOwnerResponse", targetNamespace = "http://tempuri.org/", className = "com.microwise.saturn.webservice.GetListByOwnerResponse")
    public ArrayOfRelicData getListByOwner(
            @WebParam(name = "startDate", targetNamespace = "http://tempuri.org/")
            XMLGregorianCalendar startDate,
            @WebParam(name = "endDate", targetNamespace = "http://tempuri.org/")
            XMLGregorianCalendar endDate,
            @WebParam(name = "ownerId", targetNamespace = "http://tempuri.org/")
            String ownerId);

}
