
package com.microwise.saturn.webservice;

import com.microwise.common.sys.ConfigFactory;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "RpService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://1.85.2.92:3328/RpService/RPService.svc?wsdl")
public class RpService
    extends Service
{

    private final static URL RPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(RpService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = RpService.class.getResource(".");
            String serviceUrl = ConfigFactory.getInstance().getConfig("webservice.properties").get("service.wsdl");
            url = new URL(baseUrl, serviceUrl);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://1.85.2.92:3328/RpService/RPService.svc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        RPSERVICE_WSDL_LOCATION = url;
    }

    public RpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RpService() {
        super(RPSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "RpService"));
    }

    /**
     * 
     * @return
     *     returns IRpService
     */
    @WebEndpoint(name = "BasicHttpBinding_IRpService")
    public IRpService getBasicHttpBindingIRpService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IRpService"), IRpService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRpService
     */
    @WebEndpoint(name = "BasicHttpBinding_IRpService")
    public IRpService getBasicHttpBindingIRpService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IRpService"), IRpService.class, features);
    }

}
