--王耕 2015-9-9
-- 文物修复，方案表与原因表
DROP TABLE IF EXISTS o_scheme;
CREATE TABLE o_scheme (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '唯一标识,自增',
  schemeId VARCHAR(50) DEFAULT NULL COMMENT '方案编号',
  name VARCHAR(120) NOT NULL COMMENT '方案名称',
  institutionId int(11) NOT NULL COMMENT '设计单位',
  confirmTime DATETIME DEFAULT NULL COMMENT '批准时间',
  confirmNum VARCHAR(50) DEFAULT NULL COMMENT '批准文号',
  siteId VARCHAR(50) DEFAULT NULL COMMENT '站点ID',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '修复方案表';

DROP TABLE IF EXISTS o_reason;
CREATE TABLE o_reason (
  id INT(11) NOT NULL AUTO_INCREMENT COMMENT '唯一标识,自增',
  repairReason VARCHAR(120) NOT NULL COMMENT '修复因由',
  siteId VARCHAR(50) DEFAULT NULL COMMENT '站点ID',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT '修复原因表';